using System;
using System.IO;
using System.Security.Cryptography;

namespace SmartFileMan.Core.Services
{
    public class PluginVerifier
    {
        // TODO: 替换为 KeyGen 生成的真实 RSA 公钥 (XML 格式)
        // TODO: Replace with a real RSA public key generated by KeyGen (XML format)
        // 只有持有对应私钥签名的插件才能通过验证
        // Only plugins signed with the corresponding private key will pass verification
        private const string PublicKeyXml = @"<RSAKeyValue><Modulus>pbFCtCZO6gfwqzkRnI6DgzAUMrV91O++3Zu8mmeEmI3aBcSGo5jOeJNwuuLPynVia6E7afYYgnxiYT88WzgGk970y2LTVg1g4zlsHLS6ACSuFry0vJ7vpFFIuoGF+CozCwlrGZyMSCa+MUemgbtw2znwAmVGloCjLACkzEkPB5Hv+qTq4y5ue6wQXaEXo5OzMukN8lYGF3wDwX9jP2MuPJplpuSdK35wgpGonOiT6dG87aQD5HGMca4Ck1z3wb/i8rdhS2hukV5ETQKywpNEztcCHIpI4BALScA34r08YVYVN9UHSSW+jE97w0fqHgY7Bz6NIw72hI6yQBChYC11mQ==</Modulus><Exponent>AQAB</Exponent></RSAKeyValue>";

        /// <summary>
        /// 验证插件 DLL 是否被篡改
        /// Verify if the plugin DLL has been tampered with
        /// </summary>
        /// <param name="dllPath">插件 DLL 路径 / Plugin DLL path</param>
        /// <returns>验证通过返回 true / True if verification passes</returns>
        public bool VerifyPlugin(string dllPath)
        {
            // 1. Check if the corresponding signature file (.sig) exists
            string sigPath = dllPath + ".sig";
            if (!File.Exists(sigPath))
            {
                System.Diagnostics.Debug.WriteLine($"[Security] Plugin {Path.GetFileName(dllPath)} missing signature file. Load rejected.");
                return false;
            }

            try
            {
                // 2. Read file data
                byte[] data = File.ReadAllBytes(dllPath);
                byte[] signature = File.ReadAllBytes(sigPath);

                // 3. Perform RSA verification
                using (var rsa = RSA.Create())
                {
                    try 
                    {
                        rsa.FromXmlString(PublicKeyXml);
                    }
                    catch
                    {
                        // If the key format is incorrect , return error or pretend to pass verification
                        // To avoid confusing users on first use, return false if the public key is invalid
                        System.Diagnostics.Debug.WriteLine("[Security] Verification failed due to invalid Public Key configuration.");
                        return false; 
                    }

                    bool isValid = rsa.VerifyData(data, signature, HashAlgorithmName.SHA256, RSASignaturePadding.Pkcs1);
                    
                    if (!isValid)
                    {
                        System.Diagnostics.Debug.WriteLine($"[Security] Plugin {Path.GetFileName(dllPath)} signature verification failed. File may be tampered.");
                    }

                    return isValid;
                }
            }
            catch (Exception ex)
            {
                System.Diagnostics.Debug.WriteLine($"[Verification Exception] {ex.Message}");
                return false;
            }
        }
    }
}
